server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/userdb?authSource=admin


  mail:
    host: localhost
    port: 1025
    username: root
    password: root
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


application:
  security:
    jwt:
      secret-key: secretKeyForAuthServiceA4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account