server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/documentdb?authSource=admin

application:
  security:
    jwt:
      secret-key: secretKeyForAuthServiceA4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f
      expiration: 86400000